apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: alexbrausen-deployment
spec:
  selector:
    matchLabels:
      app: alexbrausen
  replicas: 2
  template:
    metadata:
      labels:
        app: alexbrausen
    spec:
      containers:
      - name: alexbrausen-server
        image: brausen42/alexbrausen_server:initial
        ports:
        - containerPort: 80