apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: alexbrausen.com
spec:
  selector:
    matchLabels:
      app: alexbrausen_secure
  replicas: 2
  template:
    metadata:
      labels:
        app: alexbrausen_secure
    spec:
      containers:
      - name: alexbrausen-server
        image: brausen42/alexbrausen_server:v0.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080